version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: yarn dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"